"""add ingestion payloads

Revision ID: 72251d9f630f
Revises: 289e5e5494da
Create Date: 2026-07-22 18:54:23.223347

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72251d9f630f"
down_revision: str | Sequence[str] | None = "289e5e5494da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_payloads",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("staged_path", sa.String(length=1024), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "size_bytes >= 0",
            name=op.f("ck_ingestion_payloads_ingestion_payload_size_bytes_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_ingestion_payloads_job_id_ingestion_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_ingestion_payloads")),
        sa.UniqueConstraint("staged_path", name=op.f("uq_ingestion_payloads_staged_path")),
    )
    op.create_index(
        op.f("ix_ingestion_payloads_checksum_sha256"),
        "ingestion_payloads",
        ["checksum_sha256"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingestion_payloads_checksum_sha256"), table_name="ingestion_payloads")
    op.drop_table("ingestion_payloads")
    # ### end Alembic commands ###
